apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-moon
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: moon
roleRef:
  kind: Role
  name: {{ .Release.Name }}-moon
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
