apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Release.Name }}-moon
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: moon
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
