---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: moon
data:
  users.htpasswd: {{ .Values.htpasswd | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-licensekey
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: moon
data:
  license.key: {{ .Values.licenseKey | b64enc }}
